package com.fideuram.chart.grafici.istogramma;

import com.fideuram.chart.Chart;
import com.fideuram.chart.configuration.Colore;
import com.fideuram.chart.configuration.Configurazione;
import com.fideuram.chart.grafici.istogramma.bean.BarElement;
import com.fideuram.chart.configuration.Gruppo;
import com.fideuram.chart.grafici.istogramma.bean.Istogramma;
import com.fideuram.utils.Streamer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 * Created with
 * User: logan
 * Date: 09/07/13
 * Time: 8.49
 */
@Deprecated
//todo delete this class
public class IstogrmmaSemplice extends Chart {


    public IstogrmmaSemplice() {
        super();
    }

    public byte[] generate(Istogramma fagiolo) throws IOException {
        DefaultCategoryDataset cds=getDataset(fagiolo);

        JFreeChart chart = ChartFactory.createBarChart(fagiolo.getHeader(),
                fagiolo.getXaxis(),                              // domain axis label
                fagiolo.getYaxis(),                              // range axis label
                cds,                                             // data
                fagiolo.getConfigurazione().getOrientation(),    // orientation
                fagiolo.getConfigurazione().isLegenda(),         // Show legend
                fagiolo.getConfigurazione().isTooltip(),         // tooltips?
                false                                            // URLs?
        );
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        plot.getRangeAxis().setAutoRange(false);
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setRange(xminimo, xmassimo);

        applyChartTheme(chart);



        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        renderer.setSeriesPaint(0, fagiolo.getBarElements().get(0).getGroup().getColore().getColor());
        //renderer.setMaximumBarWidth(0.2);
        //renderer.setItemMargin(-2);              non funzionano

        renderer.setShadowVisible(fagiolo.getConfigurazione().isOmbra());
        if(fagiolo.getConfigurazione().isFlat2dGraph()){
            renderer.setBarPainter(new StandardBarPainter());
        }

        if(fagiolo.getConfigurazione().isFontObliquo()){
            CategoryAxis xAxis = (CategoryAxis)plot.getDomainAxis();
            xAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        }

        String s = temporaryDirecotry + getAutoGeneratedFileName() + "IstogrmmaSemplice.png";
        saveChart(chart, temporaryDirecotry, getAutoGeneratedFileName()+ "IstogrmmaSemplice", fagiolo.getConfigurazione().getxPixelDimension(), fagiolo.getConfigurazione().getyPixelDimension());

        byte[] stream = Streamer.getFile(s);
        new File(s).delete();
        return stream;
    }

    /**
     *
     * @param fagiolo
     * @return
     */
    private DefaultCategoryDataset getDataset(Istogramma fagiolo){
        DefaultCategoryDataset cds=new DefaultCategoryDataset();
        List<BarElement>  lista = fagiolo.getBarElements();
        for(int i=0; i<lista.size();i++){
            BarElement b= lista.get(i);
            cds.addValue(b.getValore(),fagiolo.getYaxis(),b.getAnno());
            if(i==0){
                xminimo=b.getValore();
                xmassimo=b.getValore();
            }else{
                if(b.getValore()<xminimo){
                    xminimo=b.getValore();
                }else if(b.getValore()>xmassimo){
                    xmassimo=b.getValore();
                }
            }
        }
        xminimo=xminimo-(xminimo*fagiolo.getConfigurazione().getPercentualeUpDowngridRange()/100);
        xmassimo=xmassimo + (xmassimo*fagiolo.getConfigurazione().getPercentualeUpDowngridRange()/100);
        return cds;
    }





    public static void main(String args[]) throws Exception {
        Configurazione configurazione = new Configurazione();
        configurazione.setxPixelDimension(800);
        configurazione.setyPixelDimension(450);
        configurazione.setLegenda(false);
        configurazione.setTooltip(true);
        configurazione.setFontSize(7);
        configurazione.setFontObliquo(true);
        configurazione.setOrientation(1);

        Istogramma istogramma = new Istogramma();
        istogramma.setConfigurazione(configurazione);

        istogramma.setHeader("Andamento Finanziario");
        istogramma.setYaxis("Controvalore");
        //Gruppo gruppo =new Gruppo(istogramma.getYaxis(),new Colore(31,53,124));
        Gruppo gruppo =new Gruppo(istogramma.getYaxis(),new Colore(69,114,167));
        istogramma.addBarElement(new BarElement(gruppo,8050.00,"Gennaio 12"));
        istogramma.addBarElement(new BarElement(gruppo,8100.00,"Febbraio 12"));
        istogramma.addBarElement(new BarElement(gruppo,8075.00, "Marzo 12"));
        istogramma.addBarElement(new BarElement(gruppo,8090.00,"Aprile 12"));
        istogramma.addBarElement(new BarElement(gruppo,8050.00,"Maggio 12"));
        istogramma.addBarElement(new BarElement(gruppo,8100.00,"Giugno 12"));
        istogramma.addBarElement(new BarElement(gruppo,8075.00,"Luglio 12"));
        istogramma.addBarElement(new BarElement(gruppo,8090.00,"Agosto 12"));
        istogramma.addBarElement(new BarElement(gruppo,8050.00,"Settembre 12"));
        istogramma.addBarElement(new BarElement(gruppo,8100.00,"Ottobbre 12"));
        istogramma.addBarElement(new BarElement(gruppo,8075.00,"Novembre 12"));
        istogramma.addBarElement(new BarElement(gruppo,8090.00,"Dicembre 12"));
        byte[] grafico = new  IstogrmmaSemplice().generate(istogramma);
        Streamer.saveToFile(grafico,"/tmp/","istogrammasemplice.png");
    }



}
