package com.fideuram.chart.grafici.linea;

import com.fideuram.chart.configuration.Colore;
import com.fideuram.chart.configuration.Configurazione;
import com.fideuram.chart.grafici.linea.bean.Linea;
import com.fideuram.chart.grafici.linea.bean.Punto;
import com.fideuram.utils.Streamer;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.*;
import java.awt.geom.Ellipse2D;
import java.io.File;
import java.io.IOException;
import java.util.GregorianCalendar;

/**
 * User: V801068
 * Date: 16/03/15
 * Time: 17.16
 */
public class LineaFondoCustom extends LineaSemplice{
    public LineaFondoCustom() {
        super();
    }

    @Override
    public  byte[] generate(Linea linea)throws IOException {
        configurazione=linea.getConfigurazione();
        dataset  = new DefaultCategoryDataset();
        setDataset(linea);
        CategoryAxis xAxis = new CategoryAxis(linea.getXaxis());
        if(linea.getConfigurazione().isFontObliquo()){
            xAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        }
        xAxis.setTickLabelFont(configurazione.getFontLabels());
        xAxis.setTickLabelPaint(configurazione.getFontLabelColor().getColor());

        NumberAxis yAxis = new NumberAxis(linea.getYaxis());
        if(configurazione.getTickGrid()!=null)
            yAxis.setTickUnit(new NumberTickUnit(configurazione.getTickGrid()));
        LineAndShapeRenderer renderer = new LineAndShapeRenderer();

        renderer.setSeriesPaint(0, linea.getColore().getColor());
        renderer.setSeriesOutlinePaint(0, linea.getColore().getColor());
        renderer.setSeriesShape(0, new Ellipse2D.Double(-3, -3, 6, 6));

        //renderer.setDrawOutlines(false);
        //renderer.setUseOutlinePaint(false);


        if(!configurazione.isEvidenziaIlPunto())
            renderer.setBaseShapesVisible(false);
        //renderer.setSeriesShape(0, new Rectangle2D.Double(-3, -3, 5, 5));
        CategoryPlot plot = new CategoryPlot(dataset, xAxis, yAxis, renderer);


        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setRange(xminimo, xmassimo);
        JFreeChart chart = new JFreeChart("",
                configurazione.getFontTitolo(),
                plot,
                true);


        chart.removeLegend();
        chart.setBackgroundPaint(linea.getConfigurazione().getBackColor().getColor());
        chart.setTitle(linea.getHeader());

        // Tolgo la cornice al grafico
        chart.setBorderPaint(Color.WHITE);//questo elimin la cornice del grafico

        String s = temporaryDirecotry + getAutoGeneratedFileName() + ".png";
        saveChart(chart, temporaryDirecotry, getAutoGeneratedFileName(), linea.getConfigurazione().getxPixelDimension(), linea.getConfigurazione().getyPixelDimension());
        byte[] stream = Streamer.getFile(s);
        new File(s).delete();
        return stream;
    }


    public static void main(String args[]) throws Exception {
        Configurazione configurazione=new Configurazione();
        configurazione.setBackColor(new Colore(255,255,255));
        configurazione.setGridColor(new Colore(0, 0, 0));
        configurazione.setFontLabelColor(new Colore(146,144,132));
        configurazione.setFontLabels("HelveticaNeueLT Std Lt",12);
        configurazione.setFontTitolo("HelveticaNeueLT Std Lt",18);
        configurazione.setFontObliquo(false);
        configurazione.setCurvedLine(true);
        configurazione.setPercentualeUpDowngridRange(15);
        configurazione.setTooltip(false);
        configurazione.setLegenda(false);
        configurazione.setEvidenziaIlPunto(false);
        configurazione.setyPixelDimension(400);
        configurazione.setxPixelDimension(1000);
        //configurazione.setFontSize(12);
        configurazione.setTickGrid(10.00);


        Linea l = new Linea();
        l.setConfigurazione(configurazione);
        l.setHeader("Header");
        l.setYaxis("");
        l.setXaxis("");
        l.setColore(new Colore(34,34,34));
        l.addPunto(new Punto(new GregorianCalendar(2003,01,01).getTime(), new Double(-0.50)));
        l.addPunto(new Punto(new GregorianCalendar(2013,01,01).getTime(), new Double(-0.50)));
        l.addPunto(new Punto(new GregorianCalendar(2013,02,01).getTime(), new Double(1.80)));
        l.addPunto(new Punto(new GregorianCalendar(2013,03,01).getTime(), new Double(0.20)));
        l.addPunto(new Punto(new GregorianCalendar(2013,04,01).getTime(), new Double(0.10)));
        l.addPunto(new Punto(new GregorianCalendar(2013,05,01).getTime(), new Double(3.00)));
        l.addPunto(new Punto(new GregorianCalendar().getTime(), new Double(2.65)));

        byte[] grafico= new LineaFondoCustom().generate(l);
        Streamer.saveToFile(grafico,"C:\\Users\\v801068\\Dropbox\\Public\\Fideuram\\TEMP\\Out\\","curva.png");
    }

}
