package ws.stampe.fv.andamenti;

/**
 * Created with
 * User: logan
 * Date: 05/07/13
 * Time: 14.32
 */
public class AndamentiERisultatiMock {
    public static String getXml(){

        String s="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n" +
                "<polizza>\n" +
                "    <dataElaborazione>2013-07-05</dataElaborazione>\n" +
                "    <datiTecnici>\n" +
                "        <numeroPolizza>70006890711</numeroPolizza>\n" +
                "        <codiceConferimento>032870RS511</codiceConferimento>\n" +
                "        <stato>Attiva</stato>\n" +
                "        <sottostato>ATTIVA</sottostato>\n" +
                "        <prodotto>\n" +
                "            <codice>RS0U1</codice>\n" +
                "            <descrizione>Fideuram Vita Insieme</descrizione>\n" +
                "        </prodotto>\n" +
                "        <tariffa>\n" +
                "            <codice>931</codice>\n" +
                "            <descrizione>Vita intera a Premio Unico con  Aggiuntivi</descrizione>\n" +
                "        </tariffa>\n" +
                "        <ramoMinisteriale>3</ramoMinisteriale>\n" +
                "        <tipoPrestazione>C</tipoPrestazione>\n" +
                "        <tipoPolizza>A</tipoPolizza>\n" +
                "        <dataEmissione>2012-05-31</dataEmissione>\n" +
                "        <dataScadenza>2100-12-31</dataScadenza>\n" +
                "        <reteVendita>SPI</reteVendita>\n" +
                "    </datiTecnici>\n" +
                "    <figureContrattuali>\n" +
                "        <contraente>\n" +
                "            <personaFisica>\n" +
                "                <cognome>VETTORATO</cognome>\n" +
                "                <nome>ROMEO</nome>\n" +
                "                <codicefiscale>VTTRMO67E29C964C</codicefiscale>\n" +
                "                <datanascita>1967-05-29</datanascita>\n" +
                "                <sesso>M</sesso>\n" +
                "                <vip>false</vip>\n" +
                "            </personaFisica>\n" +
                "        </contraente>\n" +
                "        <primoAssicurato>\n" +
                "            <personaFisica>\n" +
                "                <cognome>VETTORATO</cognome>\n" +
                "                <nome>ROMEO</nome>\n" +
                "                <codicefiscale>VTTRMO67E29C964C</codicefiscale>\n" +
                "                <datanascita>1967-05-29</datanascita>\n" +
                "                <sesso>M</sesso>\n" +
                "                <vip>false</vip>\n" +
                "            </personaFisica>\n" +
                "        </primoAssicurato>\n" +
                "        <secondoAssicurato/>\n" +
                "        <beneficiarioMorte>VETTORATO MARIA 100,0%</beneficiarioMorte>\n" +
                "        <indirizzoContratto>\n" +
                "            <tipoIndirizzo>Postale</tipoIndirizzo>\n" +
                "            <indirizzo>PZZA MADRICE 24</indirizzo>\n" +
                "            <cap>91023</cap>\n" +
                "            <comune>FAVIGNANA</comune>\n" +
                "            <provincia>TP</provincia>\n" +
                "            <regione>Sicilia</regione>\n" +
                "            <nazione>Italia</nazione>\n" +
                "            <dataAggiornamento>2012-05-31</dataAggiornamento>\n" +
                "        </indirizzoContratto>\n" +
                "        <rol>\n" +
                "            <codiceStato>0</codiceStato>\n" +
                "        </rol>\n" +
                "        <banker>\n" +
                "            <privateBanker>\n" +
                "                <cognome>BONOMINI</cognome>\n" +
                "                <nome>SERGIO</nome>\n" +
                "                <codicefiscale>BNMSRG61L31B296M</codicefiscale>\n" +
                "                <datanascita>1970-01-01</datanascita>\n" +
                "                <sesso>M</sesso>\n" +
                "                <professione></professione>\n" +
                "                <titolo></titolo>\n" +
                "                <vip>true</vip>\n" +
                "            </privateBanker>\n" +
                "            <dataInizio>2012-03-01</dataInizio>\n" +
                "            <stato>Attivo</stato>\n" +
                "            <livello>Private Banker</livello>\n" +
                "        </banker>\n" +
                "    </figureContrattuali>\n" +
                "    <prestazioni>\n" +
                "        <prestazioneGarantitaUltimaRivalutazione>0.0</prestazioneGarantitaUltimaRivalutazione>\n" +
                "        <importoBonusFvInsieme>0.0</importoBonusFvInsieme>\n" +
                "        <valoreRiscattoScadenzaGarantito>0.0</valoreRiscattoScadenzaGarantito>\n" +
                "        <ipotesiValoreRiscattoScadenza>0.0</ipotesiValoreRiscattoScadenza>\n" +
                "        <valoreRiscattoAnticipato>0.0</valoreRiscattoAnticipato>\n" +
                "        <eccedenza>0.0</eccedenza>\n" +
                "        <opzioni xsi:nil=\"true\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/>\n" +
                "        <renditaACLS75Anno>0.0</renditaACLS75Anno>\n" +
                "        <renditaACLS80Anno>0.0</renditaACLS80Anno>\n" +
                "        <renditaACLS85Anno>0.0</renditaACLS85Anno>\n" +
                "        <totalePrestazioniCV>0.0</totalePrestazioniCV>\n" +
                "    </prestazioni>\n" +
                "    <finanziario>\n" +
                "        <quoteTotali>2230.79911</quoteTotali>\n" +
                "        <controvaloreTotale>34793.8957</controvaloreTotale>\n" +
                "        <dataRiferimentoNAV>2013-07-02</dataRiferimentoNAV>\n" +
                "        <andamentiRisultati>\n" +
                "            <percentualeRendimentoDaInizioGestione>-1.219</percentualeRendimentoDaInizioGestione>\n" +
                "            <percentualeRendimentoDaInizioAnno>-4.65054</percentualeRendimentoDaInizioAnno>\n" +
                "            <percentualeRendimentoDaInizioTrimestre>0.4105</percentualeRendimentoDaInizioTrimestre>\n" +
                "            <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "            <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "            <dataCalcoloBF>2013-07-04</dataCalcoloBF>\n" +
                "            <annoRiferimento>2013</annoRiferimento>\n" +
                "            <premioInizialeVersato>35440.0</premioInizialeVersato>\n" +
                "            <premiVersatiInAnnoRiferimento>0.0</premiVersatiInAnnoRiferimento>\n" +
                "            <premioInizialeVersatoDaInizioGestione>35440.0</premioInizialeVersatoDaInizioGestione>\n" +
                "            <premiVersatiDaInizioGestione>35440.0</premiVersatiDaInizioGestione>\n" +
                "            <importiRiscattatiInAnnoRiferimento>0.0</importiRiscattatiInAnnoRiferimento>\n" +
                "            <importiRiscattatiDaInizioGestione>0.0</importiRiscattatiDaInizioGestione>\n" +
                "            <cedoleErogateInAnnoRiferimento>0.0</cedoleErogateInAnnoRiferimento>\n" +
                "            <cedoleErogateDaInizioGestione>0.0</cedoleErogateDaInizioGestione>\n" +
                "            <controvaloreTotale>34793.8957</controvaloreTotale>\n" +
                "            <dataRiferimentoNav>2013-07-02</dataRiferimentoNav>\n" +
                "            <risultatoAnnuoInAnnoRiferimento>-1871.0</risultatoAnnuoInAnnoRiferimento>\n" +
                "            <risultatoAnnuoDaInizioGestione>-646.0</risultatoAnnuoDaInizioGestione>\n" +
                "            <capitaleCasoMorte>0.0</capitaleCasoMorte>\n" +
                "            <quoteTotale>2230.79911</quoteTotale>\n" +
                "            <andamentoTir>\n" +
                "                <valore>0.0</valore>\n" +
                "                <data>2012-05-31</data>\n" +
                "                <descrizione>Data Sottoscrizione</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>-0.5766</valore>\n" +
                "                <data>2012-06-29</data>\n" +
                "                <descrizione>Rendimento al 29/06/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>0.73824</valore>\n" +
                "                <data>2012-07-31</data>\n" +
                "                <descrizione>Rendimento al 31/07/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>1.45093</valore>\n" +
                "                <data>2012-08-31</data>\n" +
                "                <descrizione>Rendimento al 31/08/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>2.07001</valore>\n" +
                "                <data>2012-09-28</data>\n" +
                "                <descrizione>Rendimento al 28/09/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>1.71584</valore>\n" +
                "                <data>2012-10-31</data>\n" +
                "                <descrizione>Rendimento al 31/10/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>3.00177</valore>\n" +
                "                <data>2012-11-30</data>\n" +
                "                <descrizione>Rendimento al 30/11/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>3.45728</valore>\n" +
                "                <data>2012-12-31</data>\n" +
                "                <descrizione>Rendimento al 31/12/2012</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>2.5374</valore>\n" +
                "                <data>2013-01-31</data>\n" +
                "                <descrizione>Rendimento al 31/01/2013</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>2.81277</valore>\n" +
                "                <data>2013-02-28</data>\n" +
                "                <descrizione>Rendimento al 28/02/2013</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>3.72498</valore>\n" +
                "                <data>2013-03-29</data>\n" +
                "                <descrizione>Rendimento al 29/03/2013</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>4.4608</valore>\n" +
                "                <data>2013-04-30</data>\n" +
                "                <descrizione>Rendimento al 30/04/2013</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <andamentoTir>\n" +
                "                <valore>2.17546</valore>\n" +
                "                <data>2013-05-31</data>\n" +
                "                <descrizione>Rendimento al 31/05/2013</descrizione>\n" +
                "            </andamentoTir>\n" +
                "            <controvaloreTotaleAnnoPrecedente>36665.2168</controvaloreTotaleAnnoPrecedente>\n" +
                "            <dataControvaloreTotaleAnnoPrecedente>2012-12-28</dataControvaloreTotaleAnnoPrecedente>\n" +
                "            <isTirAnomalo>false</isTirAnomalo>\n" +
                "            <dataRiferimentoConsolidato>31/05/2013</dataRiferimentoConsolidato>\n" +
                "            <statisticheRendimentoAndamentoFondi>\n" +
                "                <statistiche>\n" +
                "                    <codice>FO018</codice>\n" +
                "                    <descrizione>FONDITALIA INFLATION LINKED \"T\"</descrizione>\n" +
                "                    <valoreFront>0.0</valoreFront>\n" +
                "                    <dataRiferimento>2013-05-31</dataRiferimento>\n" +
                "                    <dati>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-0.9278</valore>\n" +
                "                            <valoreDaInizioAnno>-0.9278</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-0.9278</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.9278</valoreDelTrimestre>\n" +
                "                            <data>2012-06-29</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-06-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 29/06/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-0.212</valore>\n" +
                "                            <valoreDaInizioAnno>-0.212</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-0.212</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.0165</valoreDelTrimestre>\n" +
                "                            <data>2012-07-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 31/07/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>0.1134</valore>\n" +
                "                            <valoreDaInizioAnno>0.1134</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>0.1134</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.3461</valoreDelTrimestre>\n" +
                "                            <data>2012-08-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 31/08/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>0.151</valore>\n" +
                "                            <valoreDaInizioAnno>0.151</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>0.151</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.4936</valoreDelTrimestre>\n" +
                "                            <data>2012-09-28</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 28/09/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>0.1854</valore>\n" +
                "                            <valoreDaInizioAnno>0.1854</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>0.1854</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.0343</valoreDelTrimestre>\n" +
                "                            <data>2012-10-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 31/10/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.4997</valore>\n" +
                "                            <valoreDaInizioAnno>1.4997</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.4997</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.3466</valoreDelTrimestre>\n" +
                "                            <data>2012-11-30</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 30/11/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.2908</valore>\n" +
                "                            <valoreDaInizioAnno>2.2908</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.2908</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>2.1365</valoreDelTrimestre>\n" +
                "                            <data>2012-12-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 31/12/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.41711</valore>\n" +
                "                            <valoreDaInizioAnno>-0.97244</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.41711</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.97244</valoreDelTrimestre>\n" +
                "                            <data>2013-01-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 31/01/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.34508</valore>\n" +
                "                            <valoreDaInizioAnno>-1.10903</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.34508</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-1.10903</valoreDelTrimestre>\n" +
                "                            <data>2013-02-28</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 28/02/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.54187</valore>\n" +
                "                            <valoreDaInizioAnno>0.17168</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.54187</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.17168</valoreDelTrimestre>\n" +
                "                            <data>2013-03-29</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 29/03/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>3.12528</valore>\n" +
                "                            <valoreDaInizioAnno>0.772</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>3.12528</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.6094</valoreDelTrimestre>\n" +
                "                            <data>2013-04-30</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 30/04/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>0.12376</valore>\n" +
                "                            <valoreDaInizioAnno>-2.51366</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>0.12376</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-2.7207</valoreDelTrimestre>\n" +
                "                            <data>2013-05-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA INFLATION LINKED \"T\" al 31/05/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                    </dati>\n" +
                "                </statistiche>\n" +
                "                <statistiche>\n" +
                "                    <codice>IV006</codice>\n" +
                "                    <descrizione>INVESCO BALANCED RISK ALLOCATION \"C\"</descrizione>\n" +
                "                    <valoreFront>0.0</valoreFront>\n" +
                "                    <dataRiferimento>2013-05-31</dataRiferimento>\n" +
                "                    <dati>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-0.2909</valore>\n" +
                "                            <valoreDaInizioAnno>-0.2909</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-0.2909</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.2909</valoreDelTrimestre>\n" +
                "                            <data>2012-06-29</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-06-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 29/06/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.907</valore>\n" +
                "                            <valoreDaInizioAnno>2.907</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.907</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>2.9818</valoreDelTrimestre>\n" +
                "                            <data>2012-07-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 31/07/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>4.3594</valore>\n" +
                "                            <valoreDaInizioAnno>4.3594</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>4.3594</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>4.4353</valoreDelTrimestre>\n" +
                "                            <data>2012-08-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 31/08/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>5.7392</valore>\n" +
                "                            <valoreDaInizioAnno>5.7392</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>5.7392</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>5.356</valoreDelTrimestre>\n" +
                "                            <data>2012-09-28</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 28/09/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>3.9027</valore>\n" +
                "                            <valoreDaInizioAnno>3.9027</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>3.9027</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-1.7368</valoreDelTrimestre>\n" +
                "                            <data>2012-10-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 31/10/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>5.5646</valore>\n" +
                "                            <valoreDaInizioAnno>5.5646</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>5.5646</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.1651</valoreDelTrimestre>\n" +
                "                            <data>2012-11-30</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 30/11/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>5.4923</valore>\n" +
                "                            <valoreDaInizioAnno>5.4923</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>5.4923</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.2334</valoreDelTrimestre>\n" +
                "                            <data>2012-12-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 31/12/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>6.15531</valore>\n" +
                "                            <valoreDaInizioAnno>0.63387</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>6.15531</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.63387</valoreDelTrimestre>\n" +
                "                            <data>2013-01-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 31/01/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>6.11179</valore>\n" +
                "                            <valoreDaInizioAnno>0.42572</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>6.11179</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.42572</valoreDelTrimestre>\n" +
                "                            <data>2013-02-28</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 28/02/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>7.43593</valore>\n" +
                "                            <valoreDaInizioAnno>1.79227</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>7.43593</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.79252</valoreDelTrimestre>\n" +
                "                            <data>2013-03-29</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 29/03/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>8.00672</valore>\n" +
                "                            <valoreDaInizioAnno>2.2799</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>8.00672</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.472</valoreDelTrimestre>\n" +
                "                            <data>2013-04-30</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 30/04/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>6.81704</valore>\n" +
                "                            <valoreDaInizioAnno>0.78865</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>6.81704</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-1.0583</valoreDelTrimestre>\n" +
                "                            <data>2013-05-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo INVESCO BALANCED RISK ALLOCATION \"C\" al 31/05/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                    </dati>\n" +
                "                </statistiche>\n" +
                "                <statistiche>\n" +
                "                    <codice>PM004</codice>\n" +
                "                    <descrizione>PIMCO TOTAL RETURN BOND \"I\" (EURO HDG)</descrizione>\n" +
                "                    <valoreFront>0.0</valoreFront>\n" +
                "                    <dataRiferimento>2013-05-31</dataRiferimento>\n" +
                "                    <dati>\n" +
                "                        <statistiche>\n" +
                "                            <valore>0.1012</valore>\n" +
                "                            <valoreDaInizioAnno>0.1012</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>0.1012</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.1012</valoreDelTrimestre>\n" +
                "                            <data>2012-06-29</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-06-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 29/06/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.2246</valore>\n" +
                "                            <valoreDaInizioAnno>1.2246</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.2246</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.0708</valoreDelTrimestre>\n" +
                "                            <data>2012-07-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 31/07/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.6805</valore>\n" +
                "                            <valoreDaInizioAnno>1.6805</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.6805</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>1.5261</valoreDelTrimestre>\n" +
                "                            <data>2012-08-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 31/08/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.7951</valore>\n" +
                "                            <valoreDaInizioAnno>2.7951</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.7951</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>2.4315</valoreDelTrimestre>\n" +
                "                            <data>2012-09-28</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-07-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 28/09/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.5261</valore>\n" +
                "                            <valoreDaInizioAnno>2.5261</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.5261</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.2617</valoreDelTrimestre>\n" +
                "                            <data>2012-10-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 31/10/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>3.0806</valore>\n" +
                "                            <valoreDaInizioAnno>3.0806</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>3.0806</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.2777</valoreDelTrimestre>\n" +
                "                            <data>2012-11-30</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 30/11/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>3.0806</valore>\n" +
                "                            <valoreDaInizioAnno>3.0806</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>3.0806</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.2777</valoreDelTrimestre>\n" +
                "                            <data>2012-12-31</data>\n" +
                "                            <dataDaInizioAnno>2012-06-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2012-10-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 31/12/2012</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.0565</valore>\n" +
                "                            <valoreDaInizioAnno>-0.9935</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.0565</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.9935</valoreDelTrimestre>\n" +
                "                            <data>2013-01-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 31/01/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.6083</valore>\n" +
                "                            <valoreDaInizioAnno>-0.4582</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.6083</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.4582</valoreDelTrimestre>\n" +
                "                            <data>2013-02-28</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 28/02/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.7587</valore>\n" +
                "                            <valoreDaInizioAnno>-0.3123</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.7587</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.3123</valoreDelTrimestre>\n" +
                "                            <data>2013-03-29</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 29/03/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>3.3472</valore>\n" +
                "                            <valoreDaInizioAnno>0.2585</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>3.3472</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.5726</valoreDelTrimestre>\n" +
                "                            <data>2013-04-30</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 30/04/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.1515</valore>\n" +
                "                            <valoreDaInizioAnno>-1.8715</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.1515</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-1.564</valoreDelTrimestre>\n" +
                "                            <data>2013-05-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-01</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2012-06-01</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo PIMCO TOTAL RETURN BOND \"I\" (EURO HDG) al 31/05/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                    </dati>\n" +
                "                </statistiche>\n" +
                "                <statistiche>\n" +
                "                    <codice>FO015</codice>\n" +
                "                    <descrizione>FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\"</descrizione>\n" +
                "                    <valoreFront>0.0</valoreFront>\n" +
                "                    <dataRiferimento>2013-05-31</dataRiferimento>\n" +
                "                    <dati>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-0.8564</valore>\n" +
                "                            <valoreDaInizioAnno>-0.8564</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-0.8564</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.8564</valoreDelTrimestre>\n" +
                "                            <data>2013-01-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\" al 31/01/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-1.6076</valore>\n" +
                "                            <valoreDaInizioAnno>-1.6076</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-1.6076</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-1.6076</valoreDelTrimestre>\n" +
                "                            <data>2013-02-28</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\" al 28/02/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-2.2913</valore>\n" +
                "                            <valoreDaInizioAnno>-2.2913</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-2.2913</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-2.2913</valoreDelTrimestre>\n" +
                "                            <data>2013-03-29</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\" al 29/03/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-0.1359</valore>\n" +
                "                            <valoreDaInizioAnno>-0.1359</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-0.1359</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>2.2058</valoreDelTrimestre>\n" +
                "                            <data>2013-04-30</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\" al 30/04/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-3.2407</valore>\n" +
                "                            <valoreDaInizioAnno>-3.2407</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-3.2407</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.9717</valoreDelTrimestre>\n" +
                "                            <data>2013-05-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\" al 31/05/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                    </dati>\n" +
                "                </statistiche>\n" +
                "                <statistiche>\n" +
                "                    <codice>FO007</codice>\n" +
                "                    <descrizione>FONDITALIA EURO CORPORATE BOND \"T\"</descrizione>\n" +
                "                    <valoreFront>0.0</valoreFront>\n" +
                "                    <dataRiferimento>2013-05-31</dataRiferimento>\n" +
                "                    <dati>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-1.1439</valore>\n" +
                "                            <valoreDaInizioAnno>-1.1439</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-1.1439</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-1.1439</valoreDelTrimestre>\n" +
                "                            <data>2013-01-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA EURO CORPORATE BOND \"T\" al 31/01/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-0.1271</valore>\n" +
                "                            <valoreDaInizioAnno>-0.1271</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-0.1271</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.1271</valoreDelTrimestre>\n" +
                "                            <data>2013-02-28</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA EURO CORPORATE BOND \"T\" al 28/02/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>0.4342</valore>\n" +
                "                            <valoreDaInizioAnno>0.4342</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>0.4342</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.4342</valoreDelTrimestre>\n" +
                "                            <data>2013-03-29</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA EURO CORPORATE BOND \"T\" al 29/03/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.2956</valore>\n" +
                "                            <valoreDaInizioAnno>1.2956</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.2956</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.8577</valoreDelTrimestre>\n" +
                "                            <data>2013-04-30</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA EURO CORPORATE BOND \"T\" al 30/04/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>1.0953</valore>\n" +
                "                            <valoreDaInizioAnno>1.0953</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>1.0953</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>0.6582</valoreDelTrimestre>\n" +
                "                            <data>2013-05-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo FONDITALIA EURO CORPORATE BOND \"T\" al 31/05/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                    </dati>\n" +
                "                </statistiche>\n" +
                "                <statistiche>\n" +
                "                    <codice>SG003</codice>\n" +
                "                    <descrizione>JULIUS BAER EF LUXURY BRANDS \"C\" (EUR)</descrizione>\n" +
                "                    <valoreFront>0.0</valoreFront>\n" +
                "                    <dataRiferimento>2013-05-31</dataRiferimento>\n" +
                "                    <dati>\n" +
                "                        <statistiche>\n" +
                "                            <valore>-2.2402</valore>\n" +
                "                            <valoreDaInizioAnno>-2.2402</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>-2.2402</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-2.2402</valoreDelTrimestre>\n" +
                "                            <data>2013-01-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo JULIUS BAER EF LUXURY BRANDS \"C\" (EUR) al 31/01/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>2.1299</valore>\n" +
                "                            <valoreDaInizioAnno>2.1299</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>2.1299</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>2.1299</valoreDelTrimestre>\n" +
                "                            <data>2013-02-28</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo JULIUS BAER EF LUXURY BRANDS \"C\" (EUR) al 28/02/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>4.2599</valore>\n" +
                "                            <valoreDaInizioAnno>4.2599</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>4.2599</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>4.2599</valoreDelTrimestre>\n" +
                "                            <data>2013-03-29</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-01-17</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo JULIUS BAER EF LUXURY BRANDS \"C\" (EUR) al 29/03/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>3.7902</valore>\n" +
                "                            <valoreDaInizioAnno>3.7902</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>3.7902</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>-0.4505</valoreDelTrimestre>\n" +
                "                            <data>2013-04-30</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo JULIUS BAER EF LUXURY BRANDS \"C\" (EUR) al 30/04/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                        <statistiche>\n" +
                "                            <valore>6.8007</valore>\n" +
                "                            <valoreDaInizioAnno>6.8007</valoreDaInizioAnno>\n" +
                "                            <valoreDaInizioGestione>6.8007</valoreDaInizioGestione>\n" +
                "                            <valoreDelTrimestre>2.4369</valoreDelTrimestre>\n" +
                "                            <data>2013-05-31</data>\n" +
                "                            <dataDaInizioAnno>2013-01-17</dataDaInizioAnno>\n" +
                "                            <dataDaInizioGestione>2013-01-17</dataDaInizioGestione>\n" +
                "                            <dataDelTrimestre>2013-04-01</dataDelTrimestre>\n" +
                "                            <descrizione>Andamento del Fondo JULIUS BAER EF LUXURY BRANDS \"C\" (EUR) al 31/05/2013</descrizione>\n" +
                "                            <isTirAnomalo>false</isTirAnomalo>\n" +
                "                        </statistiche>\n" +
                "                    </dati>\n" +
                "                </statistiche>\n" +
                "            </statisticheRendimentoAndamentoFondi>\n" +
                "            <dettaglioComposizioneRendimentoFondo>\n" +
                "                <dettaglioRendimentoFondoRamo3>\n" +
                "                    <polizzaRiferimento>0</polizzaRiferimento>\n" +
                "                    <codiceFondo>FO018</codiceFondo>\n" +
                "                    <denominazioneFondoInvestimento>FONDITALIA INFLATION LINKED \"T\"</denominazioneFondoInvestimento>\n" +
                "                    <valoreNAV>0.0</valoreNAV>\n" +
                "                    <dataNav>2013-07-02</dataNav>\n" +
                "                    <numeroQuote>905.57914</numeroQuote>\n" +
                "                    <controvaloreQuote>14086.2835</controvaloreQuote>\n" +
                "                    <isin>LU0388709981</isin>\n" +
                "                    <idRepository>0</idRepository>\n" +
                "                    <percentualeRendimentoDaInizioGestione>-3.0792</percentualeRendimentoDaInizioGestione>\n" +
                "                    <percentualeRendimentoDaInizioAnno>-6.25943</percentualeRendimentoDaInizioAnno>\n" +
                "                    <percentualeRendimentoDelTrimestre>0.3095</percentualeRendimentoDelTrimestre>\n" +
                "                    <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "                    <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "                    <pesoFondo>40.4849</pesoFondo>\n" +
                "                </dettaglioRendimentoFondoRamo3>\n" +
                "                <dettaglioRendimentoFondoRamo3>\n" +
                "                    <polizzaRiferimento>0</polizzaRiferimento>\n" +
                "                    <codiceFondo>PM004</codiceFondo>\n" +
                "                    <denominazioneFondoInvestimento>PIMCO TOTAL RETURN BOND \"I\" (EURO HDG)</denominazioneFondoInvestimento>\n" +
                "                    <valoreNAV>0.0</valoreNAV>\n" +
                "                    <dataNav>2013-07-02</dataNav>\n" +
                "                    <numeroQuote>351.93406</numeroQuote>\n" +
                "                    <controvaloreQuote>6978.8524</controvaloreQuote>\n" +
                "                    <isin>IE0033989843</isin>\n" +
                "                    <idRepository>0</idRepository>\n" +
                "                    <percentualeRendimentoDaInizioGestione>-0.9578</percentualeRendimentoDaInizioGestione>\n" +
                "                    <percentualeRendimentoDaInizioAnno>-4.0015</percentualeRendimentoDaInizioAnno>\n" +
                "                    <percentualeRendimentoDelTrimestre>0.2021</percentualeRendimentoDelTrimestre>\n" +
                "                    <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "                    <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "                    <pesoFondo>20.0576</pesoFondo>\n" +
                "                </dettaglioRendimentoFondoRamo3>\n" +
                "                <dettaglioRendimentoFondoRamo3>\n" +
                "                    <polizzaRiferimento>0</polizzaRiferimento>\n" +
                "                    <codiceFondo>IV006</codiceFondo>\n" +
                "                    <denominazioneFondoInvestimento>INVESCO BALANCED RISK ALLOCATION \"C\"</denominazioneFondoInvestimento>\n" +
                "                    <valoreNAV>0.0</valoreNAV>\n" +
                "                    <dataNav>2013-07-02</dataNav>\n" +
                "                    <numeroQuote>368.83771</numeroQuote>\n" +
                "                    <controvaloreQuote>5252.249</controvaloreQuote>\n" +
                "                    <isin>LU0432616810</isin>\n" +
                "                    <idRepository>0</idRepository>\n" +
                "                    <percentualeRendimentoDaInizioGestione>2.9367</percentualeRendimentoDaInizioGestione>\n" +
                "                    <percentualeRendimentoDaInizioAnno>-3.36933</percentualeRendimentoDaInizioAnno>\n" +
                "                    <percentualeRendimentoDelTrimestre>0.7072</percentualeRendimentoDelTrimestre>\n" +
                "                    <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "                    <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "                    <pesoFondo>15.0953</pesoFondo>\n" +
                "                </dettaglioRendimentoFondoRamo3>\n" +
                "                <dettaglioRendimentoFondoRamo3>\n" +
                "                    <polizzaRiferimento>0</polizzaRiferimento>\n" +
                "                    <codiceFondo>FO015</codiceFondo>\n" +
                "                    <denominazioneFondoInvestimento>FONDITALIA BOND GLOBAL EMERGING MARKETS \"T\"</denominazioneFondoInvestimento>\n" +
                "                    <valoreNAV>0.0</valoreNAV>\n" +
                "                    <dataNav>2013-07-02</dataNav>\n" +
                "                    <numeroQuote>278.64879</numeroQuote>\n" +
                "                    <controvaloreQuote>3446.3282</controvaloreQuote>\n" +
                "                    <isin>LU0388708405</isin>\n" +
                "                    <idRepository>0</idRepository>\n" +
                "                    <percentualeRendimentoDaInizioGestione>-7.4678</percentualeRendimentoDaInizioGestione>\n" +
                "                    <percentualeRendimentoDaInizioAnno>-7.4678</percentualeRendimentoDaInizioAnno>\n" +
                "                    <percentualeRendimentoDelTrimestre>0.7742</percentualeRendimentoDelTrimestre>\n" +
                "                    <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "                    <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "                    <pesoFondo>9.9049</pesoFondo>\n" +
                "                </dettaglioRendimentoFondoRamo3>\n" +
                "                <dettaglioRendimentoFondoRamo3>\n" +
                "                    <polizzaRiferimento>0</polizzaRiferimento>\n" +
                "                    <codiceFondo>FO007</codiceFondo>\n" +
                "                    <denominazioneFondoInvestimento>FONDITALIA EURO CORPORATE BOND \"T\"</denominazioneFondoInvestimento>\n" +
                "                    <valoreNAV>0.0</valoreNAV>\n" +
                "                    <dataNav>2013-07-02</dataNav>\n" +
                "                    <numeroQuote>315.43539</numeroQuote>\n" +
                "                    <controvaloreQuote>2976.4483</controvaloreQuote>\n" +
                "                    <isin>LU0388707266</isin>\n" +
                "                    <idRepository>0</idRepository>\n" +
                "                    <percentualeRendimentoDaInizioGestione>-0.4658</percentualeRendimentoDaInizioGestione>\n" +
                "                    <percentualeRendimentoDaInizioAnno>-0.4658</percentualeRendimentoDaInizioAnno>\n" +
                "                    <percentualeRendimentoDelTrimestre>0.2338</percentualeRendimentoDelTrimestre>\n" +
                "                    <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "                    <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "                    <pesoFondo>8.5545</pesoFondo>\n" +
                "                </dettaglioRendimentoFondoRamo3>\n" +
                "                <dettaglioRendimentoFondoRamo3>\n" +
                "                    <polizzaRiferimento>0</polizzaRiferimento>\n" +
                "                    <codiceFondo>SG003</codiceFondo>\n" +
                "                    <denominazioneFondoInvestimento>JULIUS BAER EF LUXURY BRANDS \"C\" (EUR)</denominazioneFondoInvestimento>\n" +
                "                    <valoreNAV>0.0</valoreNAV>\n" +
                "                    <dataNav>2013-07-02</dataNav>\n" +
                "                    <numeroQuote>10.36402</numeroQuote>\n" +
                "                    <controvaloreQuote>2053.7342</controvaloreQuote>\n" +
                "                    <isin>LU0329430473</isin>\n" +
                "                    <idRepository>0</idRepository>\n" +
                "                    <percentualeRendimentoDaInizioGestione>3.0309</percentualeRendimentoDaInizioGestione>\n" +
                "                    <percentualeRendimentoDaInizioAnno>3.0309</percentualeRendimentoDaInizioAnno>\n" +
                "                    <percentualeRendimentoDelTrimestre>0.706</percentualeRendimentoDelTrimestre>\n" +
                "                    <percentualeRendimentoDaInizioMese>0.0</percentualeRendimentoDaInizioMese>\n" +
                "                    <percentualeRendimentoDaSemestre>0.0</percentualeRendimentoDaSemestre>\n" +
                "                    <pesoFondo>5.9025</pesoFondo>\n" +
                "                </dettaglioRendimentoFondoRamo3>\n" +
                "            </dettaglioComposizioneRendimentoFondo>\n" +
                "        </andamentiRisultati>\n" +
                "    </finanziario>\n" +
                "    <contabile>\n" +
                "        <totalePremiAnnuiIncassati>35440.0</totalePremiAnnuiIncassati>\n" +
                "        <totalePremiAggiuntiviOggi>0.0</totalePremiAggiuntiviOggi>\n" +
                "        <sommaPremiResiduiDaVersare>0.0</sommaPremiResiduiDaVersare>\n" +
                "        <dataFinePagamentoPremi>2012-05-31</dataFinePagamentoPremi>\n" +
                "    </contabile>\n" +
                "    <altriDati>\n" +
                "        <vincolo>\n" +
                "            <attivo>false</attivo>\n" +
                "        </vincolo>\n" +
                "        <decumuloCedola>\n" +
                "            <attivo>false</attivo>\n" +
                "            <dettagli>\n" +
                "                <imponibile>0.0</imponibile>\n" +
                "                <importoPagato>0.0</importoPagato>\n" +
                "                <cvn>0.0</cvn>\n" +
                "                <percentuale>0.0</percentuale>\n" +
                "                <importoRata>0.0</importoRata>\n" +
                "            </dettagli>\n" +
                "        </decumuloCedola>\n" +
                "        <imponibileCongelamento>0.0</imponibileCongelamento>\n" +
                "        <classeCPP>C</classeCPP>\n" +
                "        <percentualeCaricamentoCPP>0.0</percentualeCaricamentoCPP>\n" +
                "        <caricamentiCPP>\n" +
                "            <caricamentoCPPR3>\n" +
                "                <descrizione>Premio Unico</descrizione>\n" +
                "                <tipo_titolo>02</tipo_titolo>\n" +
                "                <percentualeCaricamento>0.0</percentualeCaricamento>\n" +
                "            </caricamentoCPPR3>\n" +
                "        </caricamentiCPP>\n" +
                "        <importoPianoProgrammatoVersamenti>35440.0</importoPianoProgrammatoVersamenti>\n" +
                "        <detraibilitaFiscale>\n" +
                "            <stato>false</stato>\n" +
                "        </detraibilitaFiscale>\n" +
                "        <polizzaDerivanteDaTrasformazione>false</polizzaDerivanteDaTrasformazione>\n" +
                "        <polizzaScudata>false</polizzaScudata>\n" +
                "        <impostaBolloMaturata>0.0</impostaBolloMaturata>\n" +
                "    </altriDati>\n" +
                "    <trasformabile>false</trasformabile>\n"+
                "</polizza>";
        return s;
    }
}
