package com.fideuram.processo.rendiconti.ante;

import com.fideuram.exception.RendicontiException;
import com.fideuram.processo.rendiconti.ProcessoGenericoRendiconti;
import com.fideuram.stampe.modello.rendiconti.mock.ante551.Ante551PRTFMock;
import com.fideuram.stampe.modello.rendiconti.prodotto.ante551.Prtf;

import java.io.File;

/**
 * Created with
 * User: v801068
 * Date: 27/01/14
 * Time: 10.31
 */
public class ProcessoAnte551Prtf extends ProcessoGenericoRendiconti {
    public ProcessoAnte551Prtf() {
        super();
    }

    public byte[] stampa(Prtf prtf) throws RendicontiException {
        normativaProdottoAllegato=prtf;
        return start("RendicontoAnte551Prtf.odt",false);
    }

    public static void main(String arga[]) throws RendicontiException {
        new ProcessoAnte551Prtf().stampa(Ante551PRTFMock.getPrtfMock());
    }

    public static String getXml(){
       return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n" +
               "<Prtf>\n" +
               "    <dataRiferimento>2014-02-10T16:31:40.913+01:00</dataRiferimento>\n" +
               "    <fondi>\n" +
               "        <codiceFondo>LA001</codiceFondo>\n" +
               "        <descrizioneFondo>PORTFOLIO AGGRESSIVO</descrizioneFondo>\n" +
               "        <volatilitaProspettica>\n" +
               "            <percVolatilitaProspettica>From 0,1000 To 0,2499</percVolatilitaProspettica>\n" +
               "            <percVolatilitaEffettiva>7.54</percVolatilitaEffettiva>\n" +
               "        </volatilitaProspettica>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2003</anno>\n" +
               "            <percFondo>9.39</percFondo>\n" +
               "            <percBM>6.54</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2004</anno>\n" +
               "            <percFondo>-10.78</percFondo>\n" +
               "            <percBM>5.28</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2005</anno>\n" +
               "            <percFondo>15.53</percFondo>\n" +
               "            <percBM>18.24</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2006</anno>\n" +
               "            <percFondo>3.2</percFondo>\n" +
               "            <percBM>3.34</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2007</anno>\n" +
               "            <percFondo>-2.36</percFondo>\n" +
               "            <percBM>0.2</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2008</anno>\n" +
               "            <percFondo>-29.7</percFondo>\n" +
               "            <percBM>-26.5</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2009</anno>\n" +
               "            <percFondo>22.06</percFondo>\n" +
               "            <percBM>21.28</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2010</anno>\n" +
               "            <percFondo>12.52</percFondo>\n" +
               "            <percBM>14.52</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2011</anno>\n" +
               "            <percFondo>-10.78</percFondo>\n" +
               "            <percBM>-3.18</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>9.39</percFondo>\n" +
               "            <percBM>8.74</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2011</anno>\n" +
               "            <percFondo>10.02</percFondo>\n" +
               "            <percBM>10.02</percBM>\n" +
               "            <mese>12</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.52</percFondo>\n" +
               "            <percBM>10.33</percBM>\n" +
               "            <mese>1</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.7</percFondo>\n" +
               "            <percBM>10.47</percBM>\n" +
               "            <mese>2</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.78</percFondo>\n" +
               "            <percBM>10.55</percBM>\n" +
               "            <mese>3</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.63</percFondo>\n" +
               "            <percBM>10.54</percBM>\n" +
               "            <mese>4</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.36</percFondo>\n" +
               "            <percBM>10.36</percBM>\n" +
               "            <mese>5</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.49</percFondo>\n" +
               "            <percBM>10.57</percBM>\n" +
               "            <mese>6</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.76</percFondo>\n" +
               "            <percBM>10.86</percBM>\n" +
               "            <mese>7</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.0</percFondo>\n" +
               "            <percBM>10.97</percBM>\n" +
               "            <mese>8</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.06</percFondo>\n" +
               "            <percBM>10.9</percBM>\n" +
               "            <mese>9</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.92</percFondo>\n" +
               "            <percBM>10.85</percBM>\n" +
               "            <mese>10</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.86</percFondo>\n" +
               "            <percBM>10.88</percBM>\n" +
               "            <mese>11</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>10.96</percFondo>\n" +
               "            <percBM>10.9</percBM>\n" +
               "            <mese>12</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "    </fondi>\n" +
               "    <fondi>\n" +
               "        <codiceFondo>LP001</codiceFondo>\n" +
               "        <descrizioneFondo>PORTFOLIO PRUDENTE</descrizioneFondo>\n" +
               "        <volatilitaProspettica>\n" +
               "            <percVolatilitaProspettica>From 0,0160 To 0,0399</percVolatilitaProspettica>\n" +
               "            <percVolatilitaEffettiva>3.37</percVolatilitaEffettiva>\n" +
               "        </volatilitaProspettica>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2003</anno>\n" +
               "            <percFondo>7.05</percFondo>\n" +
               "            <percBM>2.58</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2004</anno>\n" +
               "            <percFondo>-1.73</percFondo>\n" +
               "            <percBM>4.89</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2005</anno>\n" +
               "            <percFondo>4.8</percFondo>\n" +
               "            <percBM>8.1</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2006</anno>\n" +
               "            <percFondo>0.89</percFondo>\n" +
               "            <percBM>-0.01</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2007</anno>\n" +
               "            <percFondo>-0.1</percFondo>\n" +
               "            <percBM>1.01</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2008</anno>\n" +
               "            <percFondo>-4.34</percFondo>\n" +
               "            <percBM>1.51</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2009</anno>\n" +
               "            <percFondo>8.38</percFondo>\n" +
               "            <percBM>7.16</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2010</anno>\n" +
               "            <percFondo>4.62</percFondo>\n" +
               "            <percBM>6.7</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2011</anno>\n" +
               "            <percFondo>-1.73</percFondo>\n" +
               "            <percBM>3.01</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>7.05</percFondo>\n" +
               "            <percBM>6.49</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2011</anno>\n" +
               "            <percFondo>11.33</percFondo>\n" +
               "            <percBM>11.33</percBM>\n" +
               "            <mese>12</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.57</percFondo>\n" +
               "            <percBM>11.48</percBM>\n" +
               "            <mese>1</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.64</percFondo>\n" +
               "            <percBM>11.49</percBM>\n" +
               "            <mese>2</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.67</percFondo>\n" +
               "            <percBM>11.56</percBM>\n" +
               "            <mese>3</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.65</percFondo>\n" +
               "            <percBM>11.57</percBM>\n" +
               "            <mese>4</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.73</percFondo>\n" +
               "            <percBM>11.72</percBM>\n" +
               "            <mese>5</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.75</percFondo>\n" +
               "            <percBM>11.73</percBM>\n" +
               "            <mese>6</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.99</percFondo>\n" +
               "            <percBM>11.94</percBM>\n" +
               "            <mese>7</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>12.09</percFondo>\n" +
               "            <percBM>12.02</percBM>\n" +
               "            <mese>8</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>12.1</percFondo>\n" +
               "            <percBM>12.03</percBM>\n" +
               "            <mese>9</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>12.1</percFondo>\n" +
               "            <percBM>12.01</percBM>\n" +
               "            <mese>10</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>12.1</percFondo>\n" +
               "            <percBM>12.04</percBM>\n" +
               "            <mese>11</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>12.13</percFondo>\n" +
               "            <percBM>12.07</percBM>\n" +
               "            <mese>12</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "    </fondi>\n" +
               "    <fondi>\n" +
               "        <codiceFondo>LS001</codiceFondo>\n" +
               "        <descrizioneFondo>PORTFOLIO SICURO</descrizioneFondo>\n" +
               "        <volatilitaProspettica>\n" +
               "            <percVolatilitaProspettica>From 0,0400 To 0,0999</percVolatilitaProspettica>\n" +
               "            <percVolatilitaEffettiva>4.31</percVolatilitaEffettiva>\n" +
               "        </volatilitaProspettica>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2003</anno>\n" +
               "            <percFondo>7.38</percFondo>\n" +
               "            <percBM>3.8</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2004</anno>\n" +
               "            <percFondo>-4.82</percFondo>\n" +
               "            <percBM>5.04</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2005</anno>\n" +
               "            <percFondo>7.46</percFondo>\n" +
               "            <percBM>11.09</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2006</anno>\n" +
               "            <percFondo>1.41</percFondo>\n" +
               "            <percBM>1.02</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2007</anno>\n" +
               "            <percFondo>-1.16</percFondo>\n" +
               "            <percBM>0.83</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2008</anno>\n" +
               "            <percFondo>-12.93</percFondo>\n" +
               "            <percBM>-7.56</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2009</anno>\n" +
               "            <percFondo>12.15</percFondo>\n" +
               "            <percBM>11.26</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2010</anno>\n" +
               "            <percFondo>7.04</percFondo>\n" +
               "            <percBM>9.04</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2011</anno>\n" +
               "            <percFondo>-4.82</percFondo>\n" +
               "            <percBM>1.16</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <rendimentoAnnuo>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>7.38</percFondo>\n" +
               "            <percBM>7.14</percBM>\n" +
               "        </rendimentoAnnuo>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2011</anno>\n" +
               "            <percFondo>10.75</percFondo>\n" +
               "            <percBM>10.75</percBM>\n" +
               "            <mese>12</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.06</percFondo>\n" +
               "            <percBM>10.94</percBM>\n" +
               "            <mese>1</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.16</percFondo>\n" +
               "            <percBM>10.99</percBM>\n" +
               "            <mese>2</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.2</percFondo>\n" +
               "            <percBM>11.06</percBM>\n" +
               "            <mese>3</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.14</percFondo>\n" +
               "            <percBM>11.06</percBM>\n" +
               "            <mese>4</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.1</percFondo>\n" +
               "            <percBM>11.12</percBM>\n" +
               "            <mese>5</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.15</percFondo>\n" +
               "            <percBM>11.18</percBM>\n" +
               "            <mese>6</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.4</percFondo>\n" +
               "            <percBM>11.41</percBM>\n" +
               "            <mese>7</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.53</percFondo>\n" +
               "            <percBM>11.5</percBM>\n" +
               "            <mese>8</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.56</percFondo>\n" +
               "            <percBM>11.49</percBM>\n" +
               "            <mese>9</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.51</percFondo>\n" +
               "            <percBM>11.46</percBM>\n" +
               "            <mese>10</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.49</percFondo>\n" +
               "            <percBM>11.49</percBM>\n" +
               "            <mese>11</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "        <valoreUnitarioQuota>\n" +
               "            <anno>2012</anno>\n" +
               "            <percFondo>11.54</percFondo>\n" +
               "            <percBM>11.51</percBM>\n" +
               "            <mese>12</mese>\n" +
               "        </valoreUnitarioQuota>\n" +
               "    </fondi>\n" +
               "    <hasUltimoAnnoElement>false</hasUltimoAnnoElement>\n" +
               "    <hasBiennioElemnt>false</hasBiennioElemnt>\n" +
               "    <hasTriennioElemnt>false</hasTriennioElemnt>\n" +
               "    <hasQuinquennioElemnt>false</hasQuinquennioElemnt>\n" +
               "    <hasDecennioElemnt>false</hasDecennioElemnt>\n" +
               "</Prtf>";
    }
}
